<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GtkSharp" Version="3.24.24.95" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../BandHub.FirmwareUpdate.Core/BandHub.FirmwareUpdate.Core.csproj" />
  </ItemGroup>
</Project>
